services:
  mrobosub:
    build:
      context: .
      dockerfile: Dockerfile
    # image: mrobosub/mrobosub2
    privileged: true
    ports:
      - "10000:10000"
    volumes:
      - .:/home/ubuntu/ros2_ws/src/
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=host.docker.internal:0.0
      - LIBGL_ALWAYS_INDIRECT=0
      - QT_X11_NO_MITSHM=1
    tty: true
    stdin_open: true
