version: "3"
services:
  mrobosub:
    image: mrobosub/mrobosub
    privileged: true
    ports:
      - "10000:10000"
    volumes:
      - .:/root/catkin_ws/src/mrobosub
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=host.docker.internal:0.0
      - LIBGL_ALWAYS_INDIRECT=0
      - QT_X11_NO_MITSHM=1
    tty: true
    stdin_open: true
  
# Push with:
# docker buildx build --push --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --tag mrobosub/mrobosub .
