# Global options:

[mypy]
ignore_missing_imports = True
disallow_untyped_defs = True
namespace_packages = False
packages = mrobosub_bringup,
    mrobosub_fcu,
    mrobosub_gnc,
    mrobosub_hal,
    mrobosub_lib,
    mrobosub_localization,
    mrobosub_monitoring,
    mrobosub_perception,
    mrobosub_planning,
    mrobosub_sim,
    mrobosub_teleop,
    mrobosub_tests
exclude = (?x)(^setup\.py$|^launch$|/launch/)

