/heave_pid:
  heave_pid:
    ros__parameters:
      kp: 4.0
      ki: 0.1
      kd: 1.0
      plant_topic: "state"
      setpoint_topic: "setpoint"
      enable_topic: "enable"
      controller_topic: "control_effort"
      update_rate: 1000.0
      upper_limit: 4.0
      lower_limit: -4.0
      windup_limit: 1.0