/pitch_pid:
  pitch_pid:
    ros__parameters:
      kp: 0.1
      ki: 0.0
      kd: 0.001

      plant_topic: "state"
      setpoint_topic: "setpoint"
      enable_topic: "enable"
      controller_topic: "control_effort"
      update_rate: 1000.0

      upper_limit: 999999.0
      lower_limit: -999999.0
      windup_limit: 999999.0
      update_rate: 1000.0

      # TODO!: This is a big problem these arent implemented (need to switch PID implementation)
      # angle_error: true
      # angle_wrap: 360.0