name: Run mypy

on:
  workflow_dispatch:

  push:
    paths:
      - "*.py"
      - ".github/workflows/mypy.yaml"
      - "**/mypi.ini"

  pull_request:
    paths:
      - "*.py"
      - ".github/workflows/mypy.yaml"
      - "**/mypi.ini"

jobs:
  mypy:
    runs-on: ubuntu-latest
    container:
      image: mrobosub/mrobosub
      env:
        DISPLAY: host.docker.internal:0.0
        LIBGL_ALWAYS_INDIRECT: 0
        QT_X11_NO_MITSHM: 1
      ports:
        - 10000:10000
      volumes:
        - .:/root/catkin_ws/src/mrobosub
        - /tmp/.X11-unix:/tmp/.X11-unix

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Compose
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 1
        run: docker-compose up -d --wait

      - name: Check running containers
        run: docker ps -a

      - name: Check logs
        run: docker-compose logs

      - name: Run mypy
        run: mypy mrobosub_planning
