name: Run mypy

on:
  workflow_dispatch:

  push:
    paths:
      - "*.py"
      - ".github/workflows/mypy.yaml"
      - "**/mypi.ini"

  pull_request:
    paths:
      - "*.py"
      - ".github/workflows/mypy.yaml"
      - "**/mypi.ini"

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python 3
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: python -m pip install mypy
             pip install roslibpy

      - name: Run mypy
        run: mypy mrobosub_planning
