name: Run mypy

on:
  workflow_dispatch:

  push:
    paths:
      - "*.py"
      - ".github/workflows/mypy.yaml"
      - "**/mypy.ini"

  pull_request:
    paths:
      - "*.py"
      - ".github/workflows/mypy.yaml"
      - "**/mypy.ini"

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Mypy
        run: python3 -m pip install mypy

      - name: Install Rospy
        run: pip3 install --extra-index-url https://rospypi.github.io/simple/ rospy

      - name: Run mypy
        run: mypy mrobosub_planning
